#!/usr/bin/perl -w

use Net::Twitter;
use Storable;

my $oauth_file = "oauth.dat";

my $consumer_key = "xwskIJ67lML4FJav9gdFxA";
my $consumer_secret = "aEJidCkL4d4Nj6Edg8A7H1vKwV4ZAL3azVxxEPKrDgY";

my $nt = Net::Twitter->new(
    traits            => [ 'API::REST', 'OAuth', 'RateLimit' ],
    consumer_key      => $consumer_key,
    consumer_secret   => $consumer_secret,
    ssl               => 1,
) or die;

print("Authorize this app at ", $nt->get_authorization_url, " and enter the PIN#\n");
my $pin = <STDIN>; # wait for input

chomp $pin;
# request_access_token stores the tokens in $nt AND returns them
my ( $access_token, $access_token_secret, $user_id, $screen_name ) =
    $nt->request_access_token(verifier => $pin);

# save the access tokens
my %oauth_data = (
    consumer_key => $consumer_key,
    consumer_secret => $consumer_secret,
    access_token => $access_token,
    access_token_secret => $access_token_secret,
);

store(\%oauth_data, $oauth_file);
