#!/usr/bin/perl -w

use strict;
use Config::Simple;
use Data::Dumper;

use TweetImage;
use TweetSearch;
use PrintDriver;

my $config = Config::Simple->new('config.ini');

binmode STDOUT, ':utf8'; # prevents warning about wide characters
                         # your terminal must be utf8 ready

for (;;) {
    my @tweets = TweetSearch::search($config->param('search_term'));
    foreach my $tweet ( @tweets ) {
        print("tweet from " . $tweet->{user}->{name} . "\n");
        my $image = TweetImage::create($tweet);
        PrintDriver::print($config->param('printer'), $image);

        # debug
        if ( defined $config->param("debug") and $config->param("debug") > 0 ) {
            mkdir("tweets") if ( not -e "tweets" );
            my $file_prefix = "tweets/" . $tweet->{id};
            $image->Write("$file_prefix.png");
            open(TWEET, ">", "$file_prefix.dat");
            print(TWEET Dumper($tweet));
            close(TWEET);
        }
    }
    sleep 10;
}
